version: '3'

services:
  mongodb:
      image: mongo:latest
      container_name: mongodb
      volumes:
        - mongo-data:/data/db
      ports:
        - "27017:27017"
      networks:
        - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/reverse-todo-backend:latest
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb+srv://wandrille:wandrillepw@devops-lab.sohwk.mongodb.net/reverse_todo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3001
    image: ${DOCKER_USERNAME}/reverse-todo-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:5000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge